package org.task
/*
 * This source file was generated by the Gradle 'init' task
 */
/*COMPILE:
    ./gradlew clean build
*RUN:
    ./gradlew run
*/
import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.routing.*
import repository.TaskRepository
import routes.taskRoutes

fun main() {
    embeddedServer(Netty, port = 8080) {
        module()
    }.start(wait = true)
}

fun Application.module() {
    val repo = TaskRepository()

    routing {
        taskRoutes(repo)
    }
}

